/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBitflowWebhookRouteImport } from './routes/api/public/bitflow-webhook'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBitflowWebhookRoute = ApiPublicBitflowWebhookRouteImport.update({
  id: '/api/public/bitflow-webhook',
  path: '/api/public/bitflow-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/transparencia': typeof TransparenciaRoute
  '/api/public/bitflow-webhook': typeof ApiPublicBitflowWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/transparencia': typeof TransparenciaRoute
  '/api/public/bitflow-webhook': typeof ApiPublicBitflowWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/transparencia': typeof TransparenciaRoute
  '/api/public/bitflow-webhook': typeof ApiPublicBitflowWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/transparencia' | '/api/public/bitflow-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/transparencia' | '/api/public/bitflow-webhook'
  id: '__root__' | '/' | '/transparencia' | '/api/public/bitflow-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TransparenciaRoute: typeof TransparenciaRoute
  ApiPublicBitflowWebhookRoute: typeof ApiPublicBitflowWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bitflow-webhook': {
      id: '/api/public/bitflow-webhook'
      path: '/api/public/bitflow-webhook'
      fullPath: '/api/public/bitflow-webhook'
      preLoaderRoute: typeof ApiPublicBitflowWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TransparenciaRoute: TransparenciaRoute,
  ApiPublicBitflowWebhookRoute: ApiPublicBitflowWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
